### ISSUE TITLE
bootcfg: choose a "unique port"

### ISSUE THREAD

**Issue by philips** [poseidon/matchbox#31]
It is helpful in docs and elsewhere to chose a unique port number for the config service that isn't the often used 8080. How about 9264?

**Comment by crawford** [comment]
If we do want a unique port, we should probably make sure it has been assigned (remember etcd?). What is wrong with using a common port?

**Comment by joshix** [comment]
I second the question. Isn't this exactly what 8080 is for?

If you are using 8080, it seems likely you are able to adapt the example
for your use and increment the port. 8080 is also sort of
"self-documenting" as (at least I think) people read it to imply "ephemeral
and/or site/local http service".

If the config service is going to grow to no longer match that implication,
then I also second the idea that we should work out the port and use it
"forever". 9264 is then as good as any other.

**Comment by dghubble** [comment]
The `-address` flag lets users expose the service on whatever port they want. For HTTP services 8080 was chosen since it hints at the purpose. Ideally, the service should be run as a container on a provisioner so collisions don't seem too likely.

What's the value in getting a universal (default) port number assignment and how involved is that? I suppose, if the majority of users are going to change the port when they deploy the config service, we should prescribe a good choice.

**Comment by dghubble** [comment]
What's the process for getting a port assignment?

**Comment by philips** [comment]
@crawford @dghubble You can only get a port assignment if the application is significantly recognized enough. Chicken and egg.

**Comment by philips** [comment]
@dghubble I guess I am OK with 8080 for now :-/

**Comment by dghubble** [comment]
I think we'll be needing an official port in future.
