### ISSUE TITLE
Match on DHCP-provided IP address and expose it in the metadata

### ISSUE THREAD

**Issue by barakmich** [poseidon/matchbox#363]
Suppose we get our IP through iPXE from our DHCP server, and it's not static. This should be fine, and we should be allowed to fill in the `ipv4_address` metadata field based on what was given to us, not what was statically assigned.

**Comment by dghubble** [comment]
#92 and https://github.com/coreos/coreos-baremetal/blob/master/Documentation/bootcfg.md#variables would allow this. I'm not so sure how often it is really valuable since components configured with a particular IP value need a mechanism to update that if the IP changes. But it could be done after #92.

**Comment by barakmich** [comment]
So my dream is as follows:

iPXE gets chained: with the addition of `ipv4` or similar:
```
chain ipxe?uuid=${uuid}&mac=${net0/mac:hexhyp}&domain=${domain}&hostname=${hostname}&serial=${serial}&ipv4=${net0/ip:ipv4}
```

And then with variables

```
"selector": {
  "ipv4" : "192.168.x.y"
},
"metadata": {
 "ipv4_address": "${ipv4}"
}
```

For an extra win, support "192.168.x.y/16" for the selector. ;)

The real reason is then I have one source of truth for the MAC addresses, which is my DHCP server's static/dynamic lease table.

**Comment by dghubble** [comment]
The metadata part would be do-able with #92. Wildcard selectors would be another matter entirely.
