### ISSUE TITLE
Ignition Partials

### ISSUE THREAD

**Issue by nickethier** [poseidon/matchbox#461]
I want to start a discussion around template partials. I've been making use of the Ignition append/replace configurations, but it starts to get onerous the more metadata you want to include. One reason for this is that I've got lots of duplicate configuration between my k8s-worker and k8s-controller configurations and I'd like to clean that up so its not so much of a maintenance nightmare.

It is desirable that I can pull out a lot of common duplication into a single template then use `{{ template "foo" . }}` in my main template to pull it in. One idea I had was to add an optional variable to profiles that would specify files you want to pull into the template context before rendering. I've outlined an example below.

I certainly don't thing this replaces the ignition apped/replace functionality. I think thats the first thing users should start with. However as configuration gets more complex it just isn't flexible enough for all use cases. 

I'm willing to put a PR together to make this work.

ref: #322 #230 

profiles/k8s-worker.json:
```
{
  "id": "k8s-worker",
  "name": "Kubernetes Worker",
  "boot": {
    ...
  },
  "ignition_id": "k8s-worker.yaml",
  "partials": ["k8s-common"]
}
```

partials/k8s-common.tmpl (or .yaml):
```
{{ define "k8s-common-units" }}
    - name: k8s-certs@.service
      contents: |
        [Unit]
        Description=Fetch Kubernetes certificate assets
        Requires=network-online.target
        After=network-online.target
        [Service]
        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/ssl
        ExecStart=/usr/bin/bash -c "[ -f /etc/kubernetes/ssl/%i ] || curl {{.k8s_cert_endpoint}}/tls/%i -o /etc/kubernetes/ssl/%i"
// Many other units that are shared...
{{ end }}
{{ define "k8s-common-files" }}
  - path: /etc/kubernetes/manifests/kube-proxy.yaml
  ...
{{ end }}
```

ignition/k8s-worker.yaml:
```
---
systemd:
  units:
{{ template "k8s-common-units" . }}
  <worker specific units>
storage:
  files:
{{ template "k8s-common-files" . }}
  <worker specific files>
```

**Comment by mcuadros** [comment]
I found this issue very important, we have very long files with duplicated information such as: network configuration, partition tables, sshd config, etc. We couldn't find any proper way to reuse ignition configuration across different profiles or groups, besides the appends/replace.

The appends/replaces IMHO have the following problems:
- Hard to define, you should create the profile and the groups per ignition append
- Hard to debug, if something fails you must to debug this on the client server being configured, in some cases , you need to go to a KVM over IP to investigate the issue.
- Hard to configure, since the appends are resolved by the client, the client needs access to the server, in our case we are in a VLAN, and is exactly one of the things being configured by ignition.

The solution suggested by @nickethier, is very straight forward and solve the problem. The development needed is minimal and will be very easy to maintain.

A few months ago I was working on a similar solution https://github.com/src-d/combustion/blob/master/example/install-shutdown.yaml, but I find this one more easy to understand and since is working on the templating layer doesn't mess with the ignition definition like mine.

I will be more than happy to help on the PR or even do it, if @nickethier doesn't have time in a short period of time.

**Comment by crawford** [comment]
Do YAML's anchors and tags solve your problem? All of the configuration has to be in the same document (from Matchbox's perspective), but it allows you to avoid duplication.

**Comment by mcuadros** [comment]
In a same file you don't have any problem even you can use [define/template](https://golang.org/pkg/text/template/#hdr-Nested_template_definitions) from go templates. 

The solution requested is being able to include code from another file inside of a ignition file, to avoid code duplication.

**Comment by crawford** [comment]
The go templates only work for the things that matchbox is aware of. For example, you probably wouldn't want to use templating to achieve the following:

```yaml
dropins: &systemd-debug
  - name: 00-debug.conf
    contents: |
      [Service]
      Environment=SYSTEMD_LOG_LEVEL=debug

systemd:
  units:
    - name: systemd-networkd.service
      dropins: *systemd-debug
    - name: systemd-journald.service
      dropins: *systemd-debug
```

Rereading through the original bug again makes it a bit more clear. Allowing Matchbox to combine multiple files seems like a good addition. @mcuadros thanks for your patience and walking me through the problem.

**Comment by dghubble** [comment]
Hey @mcuadros and @nickethier, thanks for the interest.

I'm finalizing acceptance of a roadmap for matchbox for the next quarter and I'll be starting active development again. Part of the renewed focus is providing new support for client applications such as the Tectonic Installer, Terraform, and command line tools which are publishing to matchbox. The theme we've seen is that over time, tools desire to do their own templating. The config transpiler is also considering adding bits of templating support as well.

For now, I'd prefer to hold off on expanding matchbox's templating system. First class integrations with client tools people already use/like is how we're thinking the customization needs of all users can be accommodated as profiles get more complex (more template logic in them).

I'm curious, are you two editing template files in the `ignition` folder and wiring up append/merge manually? Similar, to the examples or customizing those.

**Comment by mcuadros** [comment]
@dghubble, I am the author of the ignition provider for terraform. Let me now if I can do anything.

**Comment by nickethier** [comment]
@dghubble I'm doing a bit of both. We have a few common "appendable" configs that a few different profiles share (sshkeys, extra kernel modules, metrics agent, etc). All of our "main" ignition templates have the following: 

```
ignition:
  config:
    append:
{{ range $profile := .add_profiles }}
      - source: {{$.ignition_endpoint}}?profile={{$profile}}
{{end}}
```

Then in the group meta and/or metadata bundle (from #362) we define the profiles to add.

**Comment by DandyDeveloper** [comment]
@dghubble Sorry to necro an old post, but did this ever get completed? I see it's been closed but I haven't been able to find follow up on whether this ended up getting implemented.
