### ISSUE TITLE
Specify multiple MAC addresses in matchbox_group selector

### ISSUE THREAD

**Issue by alvaroaleman** [poseidon/matchbox#586]
Hi,

Is it currently possible to specify a list of MAC addresses in a matchbox_group selector and have a match if the hosts MAC address is in that list?

Regards

**Comment by dghubble** [comment]
No, `selectors` specify the required parameters or labels that incoming requests must have to be considered a match. This is a semantic AND, it does not support OR or label IN LIST kinds of matching.

**Comment by alvaroaleman** [comment]
Thanks for your answer. Are there any plans to add a in list matching for `selectors`?

Our use case are groups of hosts that have different roles/profiles, it would be great to not create a matchbox_group for each host.

**Comment by dghubble** [comment]
Yes, I think this is in-scope, just not being worked on right now.

**Comment by travisgroth** [comment]
@dghubble is there an approach you'd want taken syntax wise?  I wouldn't mind implementing but I'm undecided on how it should look; especially if backwards compat was to be maintained for existing group selectors.  An easy change might be to allow a given selector key to contain an array which is implicitly OR.  Example:

````
# Returns True if hostname matches 'host1' or 'host2'
  "selector": {
    "hostname": [
        "host1",
        "host2"
     ]
  },
````
The changes aren't trivial so I'd like an OK or guidance on a better approach before working on a PR.  Thoughts?

**Comment by dghubble** [comment]
Yes, neither the feature nor the migration impact on users is small here. It must be backwards compatible so both simple AND matching and more complex set logic can coexist for several releases (or potentially forever). We also can't afford to get the set logic wrong, its a tricky one.

Kubernetes itself went through a similar transition from simplistic AND'd selectors/labels to also supporting fully expressive set logic (though simple AND's are still the most common). I'd always planned to loosely follow that design. I'd like to avoid adding an intermediate solution (e.g. just set inclusion, like in your example), since its another thing we'll have to workaround to implement general set logic.
