### ISSUE TITLE
Ipxe eroor! Could not boot no such file or directory

### ISSUE THREAD

**Issue by lncan** [poseidon/matchbox#718]
Hi guys. I'm using ipxe to boot coreos images. I did all steps in matchbox topic. I downloaded coreos image and put all it in /var/lib/matchbox/assets. I also updated latest version for ipxe. But this error 'Could not boot no such file or directory' alway occurs each boot time.  anyone have any idea to fix that? Thanks all.

**Comment by richard-chivers** [comment]
The best way in my experience, when staring to use matchbox is to run it in the foreground so you can see the debug info. Normally it would be a mismatch in the mac address or similar.

Also make sure when starting your matchbox container that the groups part of the path points to a sub directory in the examples:


`e.g. sudo docker run -p 8080:8080 --rm -v $PWD/examples:/var/lib/matchbox:Z -v ~/matchbox/examples/groups/bootkube:/var/lib/matchbox/groups:Z quay.io/coreos/matchbox:latest -address=0.0.0.0:8080 -log-level=debug`

If you missed the /examples/groups/**bootkube** it does not appear to work (for me anyhow).

Essentially when your box boots you should see a line like 

time="2018-09-22T06:32:09Z" level=info msg="HTTP GET /ipxe?uuid=xxxxxxxx&mac=xxxxxx&domain=hq-kube.com&hostname=xxx

Once you see that it then generally becomes obvious where the issue is. I am also fairly new too, so excuse any misdirections or similar :)

Hope this helps.

**Comment by richard-chivers** [comment]
When you say why? Why what sorry. I am fairly new to matchbox too....

**Comment by lncan** [comment]
Yep. Thank you. You're very kind of man.

**Comment by dghubble** [comment]
If you choose to use the file serving feature (assets), its mentioned in that document. https://github.com/poseidon/matchbox/blob/master/Documentation/deployment.md#download-container-linux-optional

Looks like you found the solution :+1:
