### ISSUE TITLE
Documentation to use local files storage>files>contents>local

### ISSUE THREAD

**Issue by snowkiterdude** [poseidon/matchbox#760]
I would like to use local files on the matchbox server.
e.g. storage>files>contents>local instead of storage>files>contents>inline

The documentation(https://coreos.com/os/docs/latest/configuration.html) specifies that you have to pass the --files-dir flag to ct however there does not appear to be such a flag in matchbox.
How do I set the --files-dir flag?

Error:
level=error msg="error converting Container Linux config: error at line 1234, column 12\nlocal files require setting the --files-dir flag to the directory that contains the file"

Trying to set the flag:
/usr/bin/docker run --rm --name matchbox -p 8080:8080 -v /var/lib/matchbox:/var/lib/matchbox:Z -v /etc/matchbox:/etc/matchbox:Z,ro quay.io/coreos/matchbox:latest -address=0.0.0.0:8080 -log-level=debug --files-dir=/var/lib/matchbox/files
flag provided but not defined: -files-dir
Usage of /matchbox:
...

**Comment by dghubble** [comment]
Those docs are for the [ct](https://github.com/coreos/container-linux-config-transpiler) command line tool, not for Matchbox. Its a feature in `ct` since its a CLI invoked from your laptop where you may have small files to reference. With a Matchbox server, define those files in `inline` in the CLC document.

See examples: https://github.com/poseidon/matchbox/blob/master/examples/ignition/install-reboot.yaml#L21
