### ISSUE TITLE
Fedora CoreOS Config Transpiler (fcct) and Fedora CoreOS Configuration (FCC) files?

### ISSUE THREAD

**Issue by ashak** [poseidon/matchbox#786]
In trying to test out Fedora CoreOS it seems that the format of the yaml files that are used to create ignition files is changing? They seem to be referred to as Fedora CoreOS Configuration (FCC) files (details about the format are at [https://docs.fedoraproject.org/en-US/fedora-coreos/fcct-config/](https://docs.fedoraproject.org/en-US/fedora-coreos/fcct-config/)).

I noticed there was a get-fedora-coreos script to populate assets with Fedora CoreOS so I blindly assumed that this new file format may also be supported and some sort of magic would be able to tell whether to convert my yaml files using ct or fcct depending on the the content of the file to convert it to an ignition file on the fly.

I don't see any obvious mention of fcct in the code, so assuming i'm not being really dumb, is there any plan to support these FCC files and transpiling them with fcct in matchbox?

If I am being dumb is there documentation on how to use Fedora CoreOS with Matchbox?

**Comment by dghubble** [comment]
Fedora CoreOS is supported, but transpiling Fedora CoreOS Configs (FCCs) is not.

Prepare (e.g. transpile) an Ignition document and provide it to Matchbox via the Ignition [gRPC API](https://matchbox.psdn.io/api-grpc/) or via file (discouraged). Matchbox can serve Ignition v2.2 or Ignition v3.0 to support Container Linux and Fedora CoreOS.

Focus has been shifting away from Matchbox doing the templating/transpiling at serve-time to leveraging tools (e.g. Terraform templating + [terraform-provider-ct](https://github.com/poseidon/terraform-provider-ct) transpile plugin) to providing Matchbox with the valid Ignition. Tools validate configs early (errors in original context, line numbers, optional strictness, etc) rather than having Matchbox error when a machine is trying to boot later.

For an example Terraform usage, see [typhoon](https://github.com/poseidon/typhoon) which supports Fedora CoreOS with Matchbox. If your orchestration system of choice doesn't yet transpile FCCs, you can shell out to the https://github.com/coreos/fcct tool.

**Comment by ashak** [comment]
Fair enough. Thanks for the information.
