### ISSUE TITLE
Feature Request: CRD Storage

### ISSUE THREAD

**Issue by nicolerenee** [poseidon/matchbox#809]
**Description**

I'm wanting to run matchbox inside of a Kubernetes cluster. Currently though matchbox requires persistent storage. I was thinking it would be helpful if matchbox supported storing state inside of Kubernetes CRDs. Looking through the code it looks like most of what is needed is wired up to support multiple storage drivers. I'm wiling to develop this and submit the PR, but I thought I would reach out first and see if this is a feature that you would be willing to accept.

**Comment by dghubble** [comment]
I've commented on CRDs not being the best fit before https://github.com/poseidon/matchbox/issues/654

Kubernetes CustomResources should be used for Kubernetes-related, cluster-scoped objects that extend the Kubernetes API in some way and that warrant CRUD style operations and can't otherwise be expressed in a config.

Meanwhile Matchbox is a general application serving provisioning assets. Not really related to Kubernetes or extending its APIs. Its data types are associated with physical machine inventory. And the service is usually provided to many collections of machines (which may happen to be Kubernetes clusters) so there is a mismatch btw using an in-cluster store and global resources. I'd have some concerns about being yet another app (ab)using Kubernetes for general data storage and just the scope involved (maintaining, validation). Unlike today where gRPC is the API and file stores are understood to be rather internal, with Kubernetes CRs there would be an expectation those can be edited out of band, which gets into new classes of concerns or aggregation. So I'm not really keen for it.

If you're more interested just in hosting Matchbox on Kubernetes, there are some [examples](https://github.com/poseidon/matchbox/tree/master/contrib/k8s) and any Kubernetes volume type should be suitable. I run Matchbox atop Kubernetes as well, to serve colocation sites.

**Comment by dghubble** [comment]
Is your underlying issue uncertainty about providing a volume or a separate usage?

**Comment by nicolerenee** [comment]
Yeah ultimately I was trying to avoid needing to provide store in the cluster I wanted to run matchbox in. I completely agree that it would be abusing the custom resources of Kubernetes, so I will instead move forward with finding a way to provide storage. Thanks
